# Generated by Django 6.0.1 on 2026-03-01 17:00
from django.db import migrations
from django.utils.text import slugify



def populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')

    pets = [
        dict(name='Fluffy', date_of_birth='2018-05-20', personal_photo='https://example.com/photos/fluffy.jpg'),
        dict(name='Buddy', date_of_birth='2019-09-24', personal_photo='https://example.com/photos/buddy.jpg'),
        dict(name='Whiskers', date_of_birth='2017-11-03', personal_photo='https://example.com/photos/whiskers.jpg'),
        dict(name='Max', date_of_birth='2014-02-28', personal_photo='https://example.com/photos/max.jpg'),
        dict(name='Bella', date_of_birth='2015-07-21', personal_photo='https://example.com/photos/bella.jpg'),
    ]

    for data in pets:
        PetModel.objects.create(
            **data,
            slug=slugify(data["name"]),
        )


def reverse_populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=populate_pet_model, reverse_code=reverse_populate_pet_model)
    ]
