# Generated by Django 6.0.1 on 2026-03-01 17:00

from django.db import migrations

def populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.bulk_create([
        PetModel(name='Fluffy', date_of_birth='2018-05-20', personal_photo='https://example.com/photos/fluffy.jpg'),
        PetModel(name='Buddy', date_of_birth='2019-09-24', personal_photo='https://example.com/photos/buddy.jpg'),
        PetModel(name='Whiskers', date_of_birth='2017-11-03', personal_photo='https://example.com/photos/whiskers.jpg'),
        PetModel(name='Max', date_of_birth='2014-02-29', personal_photo='https://example.com/photos/max.jpg'),
        PetModel(name='Bella', date_of_birth='2015-07-21', personal_photo='https://example.com/photos/bella.jpg'),
    ])

def reverse_populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=populate_pet_model)
    ]
