# Generated by Django 6.0.1 on 2026-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.tag'),
        ),
    ]
